name: 'Github Tag Bump and `latest` tag update'
description: 'A Github Action to update MAJOR.MINOR.PATCH tag on merge and update "latest" tag.'
author: 'Wiktor Jurasz'
credits: 'Nick Sjostrom - forked from his repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
branding:
  icon: 'git-merge'  
  color: 'purple'
