name: 'Github Tag Bump and `latest` tag update'
description: 'A Github Action to update chosen branch with MAJOR.MINOR.PATCH tag on merge.'
author: 'Kim Gault'
credits: 'Wiktor Jurasz - forked from their repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
branding:
  icon: 'git-merge'  
  color: 'purple'
